language: cpp

sudo: false

compiler:
  - gcc
  - clang

env:
  global:
   - secure: "GpJSApht+7AsuCywa7pQzXhnEZ/Gpso4m8jfGbgvt+BO3gYeq7zFxHb5xajL4Ii2dQXGBPMbURr6R1Io/0PTQUtKBxufYsW3isblcGBGGrDTUu1bMa5Euq9vvbV/rlayHPyLXwYqgDWzZJiOCXQF5uWDaMvIOFPSRkjXAJPXnyozZMhOWNY+bmsjlwvd8F6E7EPf2OuhViYB8Y3vDRatjs/eWESK92LKQB0Q2lR2mid/yYsdFVQv+o6vryYispsvEq5Kbd9qSgygcHsgOdXnFlmyOzDkXhqGzEOxYfDWsvnnEBlWOM1Oh28pNTN8+eY4B6cz0hCHk7mLgtcTy8rQcpKM4dXl+VflQ2CC1rPUvwXcFasoV6YDLfMZV4EE7cehCxqq5CjqhCae6wNwYL4e2I37XsVtzj+PkRDFTTi89AIB8rxbOIPLHnaUynBoUW7GWKj8lVJAdrYT66GQU1sYCKBb+br4wUM8vwC/QPmsbszJT3mJaJSu7xAnltANAQQUIlDaw1ifDZ+J1ScrK9c4R4+caGtMiNPEQN95sJHfJ6VfQbgfwhzzD1ko9BRwl5nrBeQYNDe5Z4Mr41JI9i6N7ycMp/pI0oLE4l5gTn5iCIhcdoRgEzNIogXAIMqo64u6FJOMCBuJTHuh+S/IyljTcfF0jjDbWUydz5pSM2RObBs="

addons:
  apt:
    sources:
    - kalakris-cmake
    - ubuntu-toolchain-r-test
    - boost-latest
    packages:
    - cmake
    - libboost1.55-dev 
    - libboost-system1.55-dev
    - libboost-iostreams1.55-dev
    - libboost-python1.55-dev
    - libboost-thread1.55-dev
    - libboost-filesystem1.55-dev
    - gcc-5
    - g++-5
  coverity_scan:
    project:
      name: "hoangmle/crave-bundle-2015-07-22"
      description: "Build submitted via Travis CI"
    notification_email: hle@informatik.uni-bremen.de
    build_command: "make"
    branch_pattern: coverity_scan

cache:
  apt: true
  directories:
  - deps-gcc
  - deps-clang

script:
  - if [[ "${CXX}" == "clang++" ]]; then export CONFIG="-d deps-clang build -b cudd -b z3"; fi
  - if [[ "${CXX}" == "g++"     ]]; then export CONFIG="-d deps-gcc build -b cudd -b boolector"; fi
  - if [ "${COVERITY_SCAN_BRANCH}" == 1 ]; then export CONFIG="skip"; fi
  - if [[ "${CONFIG}" != "skip" ]]; then export BOOST_ROOT=/usr; fi
  - if [[ "${CONFIG}" != "skip" ]]; then ./bootstrap.sh ${CONFIG}; fi
  - if [[ "${CONFIG}" != "skip" ]]; then make; fi

after_success:
  - make test

os:
  - linux
